### ISSUE TITLE
Tooltip issue: "TypeError: tooltipTrigger.outerWidth is not a function"

### ISSUE THREAD

**Issue by Arth95** [lumapps/lumX#268]
Hi!

I have some problems with tooltip. When I hover over item tooltip doesn't show up. In console it says
TypeError: tooltipTrigger.outerWidth is not a function
I think that issue come out after updating angular to 1.4 version

**Comment by malexandre** [comment]
Hi!

We have not yet tested LumX with Angular 1.4. We're only managing stable version of Angular for now. But it might be linked to jQuery instead. We did not have time to make LumX work without jQuery, and `outerWidth` is from jQuery.

Do you have jQuery in your app ?

**Comment by Arth95** [comment]
Yes I do.
Here are all js files that I am using.
![lumx](https://cloud.githubusercontent.com/assets/11191600/7678791/1f775cc2-fd57-11e4-948a-752d73b02690.jpg)

**Comment by malexandre** [comment]
From the FAQ of Angular:

    between 1.3.15 and 1.4.0 there will be a number of breaking changes

So yeah, it might not work. We won't fix it for now, only when the 1.4 will be stable as the Angular team might change everything from a non-stable version to another.

**Comment by Arth95** [comment]
Okey. Thanks for response anyway :)

**Comment by Rayjax** [comment]
same error with angular 1.3.13, on ionic based project

**Comment by SujitDeshpande** [comment]
tabs directive in a blank ionic framework app gives this error. I have angular 1.3.13 as rayjax mentioned.
